CREATE DATABASE ASP
GO

USE ASP
GO

CREATE TABLE Product (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    Avatar NVARCHAR(255),
    Price INT NOT NULL
);
GO
SELECT * FROM Product;